### ISSUE TITLE
Criar botao para gerar chaveamento

### ISSUE THREAD

**Issue by KozielGPC** [KozielGPC/championship-platform#100]
### História de Usuário Relacionada
- #30 
- #33 

### Descrição Detalhada
Na página de campeonatos, deve existir um botão para gerar/re-gerar o chaveamento do campeonato, e outro para salvar o chaveamento gerado. Deve-se também adicionar o layout do chaveamento

### Requerimentos da Tarefa

- [ ] atualizar changelog
- [ ] adicionar botao de gerar chaveamento
- [ ] adicionar opção para gerar novamente
- [ ] adicionar botão de salvar chaveamento
- [ ] adicionar layout do chaveamento gerado

**Comment by dalacquar** [comment]
Feature pronta
